"use client";

import { Loader2, Search, X } from 'lucide-react';
import { GithubIcon } from '@/components/icons/GithubIcon';
import type { Repository } from '@/lib/types';
import { useMemo, useState } from 'react';

export function CreateProjectModal({ repositories, loading, creating, onClose, onSelect }: { repositories: Repository[]; loading: boolean; creating: boolean; onClose: () => void; onSelect: (repository: Repository) => void }) {
  const [query, setQuery] = useState('');
  const filtered = useMemo(() => repositories.filter((repo) => repo.full_name.toLowerCase().includes(query.toLowerCase())), [query, repositories]);
  return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4 backdrop-blur-sm"><div className="w-full max-w-lg overflow-hidden rounded-2xl border border-white/10 bg-[#15161d] shadow-2xl"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><h2 className="text-sm font-semibold">Connect a repository</h2><p className="mt-1 text-xs text-white/35">Choose a GitHub repository to create a project.</p></div><button onClick={onClose} title="Close" className="grid h-8 w-8 place-items-center rounded-lg text-white/40 hover:bg-white/10 hover:text-white"><X className="h-4 w-4" /></button></div><div className="p-5"><div className="relative"><Search className="pointer-events-none absolute top-1/2 left-3 h-4 w-4 -translate-y-1/2 text-white/30" /><input autoFocus value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search repositories" className="h-10 w-full rounded-lg border border-white/10 bg-black/20 pr-3 pl-9 text-sm outline-none placeholder:text-white/25 focus:border-violet-300/50" /></div><div className="mt-4 max-h-72 overflow-y-auto">{loading ? <div className="flex items-center justify-center gap-2 py-12 text-xs text-white/35"><Loader2 className="h-4 w-4 animate-spin" />Loading GitHub repositories</div> : filtered.length ? filtered.map((repo) => <button disabled={creating} key={repo.id} onClick={() => onSelect(repo)} className="flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left hover:bg-white/[0.06] disabled:opacity-50"><div className="grid h-8 w-8 place-items-center rounded-lg bg-white/[0.07]"><GithubIcon className="h-4 w-4 text-white/65" /></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{repo.full_name}</div><div className="mt-1 text-[11px] text-white/30">{repo.private ? 'Private' : 'Public'} · {repo.default_branch || 'main'}</div></div>{creating ? <Loader2 className="h-4 w-4 animate-spin" /> : null}</button>) : <div className="py-10 text-center text-xs text-white/35">No repositories found.</div>}</div></div></div></div>;
}
