import { Activity, Code2, ExternalLink, Globe2, LockKeyhole, Server } from 'lucide-react';
import type { Project } from '@/lib/types';

export function ProjectOverview({ project }: { project: Project }) {
  const slug = project.githubFullName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const url = `http://${slug || 'project'}.launch.io:8000`;
  return <div><div className="grid gap-4 lg:grid-cols-[1.5fr_1fr]"><div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-semibold tracking-[0.15em] text-white/35 uppercase">Project endpoint</div><h2 className="mt-2 text-xl font-semibold">Your project is connected</h2></div><div className="grid h-10 w-10 place-items-center rounded-lg bg-emerald-400/10"><Globe2 className="h-5 w-5 text-emerald-300" /></div></div><div className="mt-8 flex items-center gap-3 rounded-lg border border-white/[0.07] bg-black/20 p-3"><div className="h-2 w-2 rounded-full bg-emerald-400" /><a href={url} target="_blank" rel="noreferrer" className="min-w-0 flex-1 truncate font-mono text-xs text-white/70 hover:text-white">{slug || 'project'}.launch.io:8000</a><ExternalLink className="h-4 w-4 text-white/35" /></div><div className="mt-5 flex items-center gap-2 text-xs text-white/35"><Code2 className="h-3.5 w-3.5" /> Branch <span className="font-mono text-white/60">{project.defaultBranch}</span></div></div><div className="rounded-xl border border-white/[0.08] bg-white/[0.025] p-5 sm:p-6"><div className="text-xs font-semibold tracking-[0.15em] text-white/35 uppercase">Runtime</div><div className="mt-6 flex items-end gap-2"><span className="text-3xl font-semibold">Ready</span><span className="mb-1 h-2 w-2 rounded-full bg-emerald-400" /></div><div className="mt-3 text-xs text-white/35">Docker container · Railpack build</div></div></div><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={Activity} label="Status" value="Operational" /><Metric icon={Server} label="Runtime" value="Container" /><Metric icon={LockKeyhole} label="Access" value="Private" /></div></div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="grid h-9 w-9 place-items-center rounded-lg bg-white/[0.06]"><Icon className="h-4 w-4 text-white/55" /></div><div><div className="text-[10px] tracking-[0.14em] text-white/30 uppercase">{label}</div><div className="mt-1 text-sm font-semibold">{value}</div></div></div>; }
