import { Code2, KeyRound, Settings, SlidersHorizontal, TerminalSquare } from 'lucide-react';
import { GithubIcon as Github } from '@/components/icons/GithubIcon';
import type { DashboardView, Project } from '@/lib/types';
import { ProjectOverview } from '@/components/dashboard/ProjectOverview';

export function ProjectView({ project, view, deploying, message, error, onDeploy, onBack }: { project: Project; view: DashboardView; deploying: boolean; message: string; error: string; onDeploy: () => void; onBack: () => void }) {
  return <div><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div><button onClick={onBack} className="mb-5 text-xs text-white/35 hover:text-white">← All projects</button><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-violet-400 to-indigo-600 text-lg font-bold">{project.name.slice(0, 1).toUpperCase()}</div><div><div className="flex items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-0.04em]">{project.name}</h1><span className="h-2 w-2 rounded-full bg-emerald-400 shadow-[0_0_10px_#34d399]" /></div><p className="mt-1 flex items-center gap-2 text-xs text-white/40"><Github className="h-3 w-3" />{project.githubFullName}</p></div></div></div><button onClick={onDeploy} disabled={deploying} className="inline-flex h-10 items-center justify-center gap-2 rounded-lg bg-white px-4 text-sm font-semibold text-black transition hover:bg-violet-100 disabled:cursor-wait disabled:opacity-60">{deploying ? 'Deploying...' : 'Deploy'}</button></div>{message && <div className="mt-6 rounded-lg border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs text-emerald-200">{message}</div>}{error && <div className="mt-6 rounded-lg border border-red-400/20 bg-red-400/10 px-3 py-2 text-xs text-red-200">{error}</div>}<div className="mt-10">{view === 'overview' && <ProjectOverview project={project} />}{view === 'logs' && <Placeholder icon={TerminalSquare} title="Deployment logs" copy="The backend does not expose deployment log reads yet. Add that endpoint when you are ready to connect this view." />}{view === 'environment' && <Placeholder icon={KeyRound} title="Environment variables" copy="The backend has an environment variable table, but no read/write routes yet." />}{view === 'settings' && <SettingsPanel project={project} />}</div></div>;
}
function Placeholder({ icon: Icon, title, copy }: { icon: typeof TerminalSquare; title: string; copy: string }) { return <div className="min-h-[360px] rounded-xl border border-dashed border-white/[0.12] bg-white/[0.02] px-6 py-20 text-center"><Icon className="mx-auto h-6 w-6 text-white/35" /><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-white/35">{copy}</p></div>; }
function SettingsPanel({ project }: { project: Project }) { return <div className="max-w-2xl"><h2 className="text-lg font-semibold">Project settings</h2><p className="mt-1 text-sm text-white/35">Source and deployment defaults.</p><div className="mt-6 space-y-4"><Row label="Project name" value={project.name} /><Row label="Repository" value={project.githubFullName} icon={<Github className="h-4 w-4" />} /><Row label="Production branch" value={project.defaultBranch} icon={<Code2 className="h-4 w-4" />} /><Row label="Build engine" value="Railpack + BuildKit" icon={<SlidersHorizontal className="h-4 w-4" />} /><Row label="Configuration" value="Managed by API" icon={<Settings className="h-4 w-4" />} /></div></div>; }
function Row({ label, value, icon }: { label: string; value: string; icon?: React.ReactNode }) { return <div className="flex items-center gap-4 rounded-xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="grid h-9 w-9 place-items-center rounded-lg bg-white/[0.06] text-white/45">{icon ?? <Settings className="h-4 w-4" />}</div><div><div className="text-[10px] tracking-[0.14em] text-white/30 uppercase">{label}</div><div className="mt-1 truncate text-sm text-white/75">{value}</div></div></div>; }
