// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: deployments.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (project_id,status) VALUES ($1,$2)
RETURNING id, project_id, status, git_branch, image_tag, log_store_path, artifact_path, created_at, updated_at
`

type CreateDeploymentParams struct {
	ProjectID pgtype.UUID
	Status    DeploymentStatus
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRow(ctx, createDeployment, arg.ProjectID, arg.Status)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Status,
		&i.GitBranch,
		&i.ImageTag,
		&i.LogStorePath,
		&i.ArtifactPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
