// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domain.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (project_id, domain_name, type)
VALUES ($1, $2, $3)
RETURNING id, project_id, domain_name, type, created_at, updated_at
`

type CreateDomainParams struct {
	ProjectID  pgtype.UUID
	DomainName string
	Type       DomainNameType
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.ProjectID, arg.DomainName, arg.Type)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DomainName,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDomainByHostname = `-- name: GetDomainByHostname :one
SELECT id, project_id, domain_name, type, created_at, updated_at FROM domains WHERE domain_name = $1
`

func (q *Queries) GetDomainByHostname(ctx context.Context, domainName string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByHostname, domainName)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DomainName,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
