// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DeploymentStatus string

const (
	DeploymentStatusBuilding  DeploymentStatus = "building"
	DeploymentStatusRunning   DeploymentStatus = "running"
	DeploymentStatusDeploying DeploymentStatus = "deploying"
	DeploymentStatusFailed    DeploymentStatus = "failed"
	DeploymentStatusQueued    DeploymentStatus = "queued"
)

func (e *DeploymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeploymentStatus(s)
	case string:
		*e = DeploymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeploymentStatus: %T", src)
	}
	return nil
}

type NullDeploymentStatus struct {
	DeploymentStatus DeploymentStatus
	Valid            bool // Valid is true if DeploymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeploymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeploymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeploymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeploymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeploymentStatus), nil
}

type DomainNameType string

const (
	DomainNameTypeSystemGenerated DomainNameType = "system_generated"
	DomainNameTypeCustom          DomainNameType = "custom"
)

func (e *DomainNameType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DomainNameType(s)
	case string:
		*e = DomainNameType(s)
	default:
		return fmt.Errorf("unsupported scan type for DomainNameType: %T", src)
	}
	return nil
}

type NullDomainNameType struct {
	DomainNameType DomainNameType
	Valid          bool // Valid is true if DomainNameType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDomainNameType) Scan(value interface{}) error {
	if value == nil {
		ns.DomainNameType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DomainNameType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDomainNameType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DomainNameType), nil
}

type HealthStatus string

const (
	HealthStatusActive   HealthStatus = "active"
	HealthStatusInactive HealthStatus = "inactive"
)

func (e *HealthStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = HealthStatus(s)
	case string:
		*e = HealthStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for HealthStatus: %T", src)
	}
	return nil
}

type NullHealthStatus struct {
	HealthStatus HealthStatus
	Valid        bool // Valid is true if HealthStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullHealthStatus) Scan(value interface{}) error {
	if value == nil {
		ns.HealthStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.HealthStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullHealthStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.HealthStatus), nil
}

type Deployment struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	Status       DeploymentStatus
	GitBranch    pgtype.Text
	ImageTag     pgtype.Text
	LogStorePath pgtype.Text
	ArtifactPath pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Domain struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	DomainName string
	Type       DomainNameType
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type EnvironmentVariable struct {
	ID        pgtype.UUID
	ProjectID pgtype.UUID
	VarsJson  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Project struct {
	ID                 pgtype.UUID
	UserID             pgtype.UUID
	Name               pgtype.Text
	ActiveDeploymentID pgtype.UUID
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type ProxyMapping struct {
	ID           pgtype.UUID
	ProjectID    pgtype.UUID
	ContainerID  pgtype.Text
	InternalIp   pgtype.Text
	AssignedPort pgtype.Text
	HealthStatus NullHealthStatus
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	GithubID  pgtype.Text
	Name      string
	Email     string
	Password  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
