// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (
    user_id,
    name,
    github_full_name,
    github_clone_url,
    default_branch
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, name, active_deployment_id, created_at, updated_at, github_full_name, github_clone_url, default_branch, port, github_webhook_id
`

type CreateProjectParams struct {
	UserID         pgtype.UUID
	Name           pgtype.Text
	GithubFullName string
	GithubCloneUrl string
	DefaultBranch  string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.UserID,
		arg.Name,
		arg.GithubFullName,
		arg.GithubCloneUrl,
		arg.DefaultBranch,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubFullName,
		&i.GithubCloneUrl,
		&i.DefaultBranch,
		&i.Port,
		&i.GithubWebhookID,
	)
	return i, err
}

const selectProjectByID = `-- name: SelectProjectByID :one
SELECT id, user_id, name, active_deployment_id, created_at, updated_at, github_full_name, github_clone_url, default_branch, port, github_webhook_id FROM projects WHERE id = $1
`

func (q *Queries) SelectProjectByID(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, selectProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.ActiveDeploymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubFullName,
		&i.GithubCloneUrl,
		&i.DefaultBranch,
		&i.Port,
		&i.GithubWebhookID,
	)
	return i, err
}
