// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proxyMapping.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProxyMapping = `-- name: CreateProxyMapping :one
INSERT INTO proxy_mappings (project_id, container_id, assigned_port, health_status) 
VALUES ($1,$2,$3,$4)
RETURNING id, project_id, container_id, internal_ip, assigned_port, health_status, created_at, updated_at
`

type CreateProxyMappingParams struct {
	ProjectID    pgtype.UUID
	ContainerID  pgtype.Text
	AssignedPort pgtype.Text
	HealthStatus NullHealthStatus
}

func (q *Queries) CreateProxyMapping(ctx context.Context, arg CreateProxyMappingParams) (ProxyMapping, error) {
	row := q.db.QueryRow(ctx, createProxyMapping,
		arg.ProjectID,
		arg.ContainerID,
		arg.AssignedPort,
		arg.HealthStatus,
	)
	var i ProxyMapping
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContainerID,
		&i.InternalIp,
		&i.AssignedPort,
		&i.HealthStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveProxyMappingByProjectID = `-- name: GetActiveProxyMappingByProjectID :one
SELECT id, project_id, container_id, internal_ip, assigned_port, health_status, created_at, updated_at FROM proxy_mappings
WHERE project_id = $1 AND health_status = 'active'
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActiveProxyMappingByProjectID(ctx context.Context, projectID pgtype.UUID) (ProxyMapping, error) {
	row := q.db.QueryRow(ctx, getActiveProxyMappingByProjectID, projectID)
	var i ProxyMapping
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ContainerID,
		&i.InternalIp,
		&i.AssignedPort,
		&i.HealthStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
