// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, github_id)
VALUES ($1, $2, $3, $4)
RETURNING id, github_id, name, email, password, created_at, updated_at
`

type CreateUserParams struct {
	Name     string
	Email    string
	Password pgtype.Text
	GithubID pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.GithubID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
