// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.query.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, password, github_id, github_access_token, github_refresh_token, github_token_expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, github_id, name, email, password, created_at, updated_at, github_access_token, github_refresh_token, github_token_expires_at
`

type CreateUserParams struct {
	Name                 string
	Email                string
	Password             pgtype.Text
	GithubID             pgtype.Text
	GithubAccessToken    pgtype.Text
	GithubRefreshToken   pgtype.Text
	GithubTokenExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.GithubID,
		arg.GithubAccessToken,
		arg.GithubRefreshToken,
		arg.GithubTokenExpiresAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAccessToken,
		&i.GithubRefreshToken,
		&i.GithubTokenExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, github_id, name, email, password, created_at, updated_at, github_access_token, github_refresh_token, github_token_expires_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAccessToken,
		&i.GithubRefreshToken,
		&i.GithubTokenExpiresAt,
	)
	return i, err
}

const getUserByGithubID = `-- name: GetUserByGithubID :one
SELECT id, github_id, name, email, password, created_at, updated_at, github_access_token, github_refresh_token, github_token_expires_at FROM users
WHERE github_id = $1 LIMIT 1
`

func (q *Queries) GetUserByGithubID(ctx context.Context, githubID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGithubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAccessToken,
		&i.GithubRefreshToken,
		&i.GithubTokenExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, name, email, password, created_at, updated_at, github_access_token, github_refresh_token, github_token_expires_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAccessToken,
		&i.GithubRefreshToken,
		&i.GithubTokenExpiresAt,
	)
	return i, err
}

const updateUserGitHubTokens = `-- name: UpdateUserGitHubTokens :one
UPDATE users
SET github_access_token = $1,
    github_refresh_token = $2,
    github_token_expires_at = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, github_id, name, email, password, created_at, updated_at, github_access_token, github_refresh_token, github_token_expires_at
`

type UpdateUserGitHubTokensParams struct {
	GithubAccessToken    pgtype.Text
	GithubRefreshToken   pgtype.Text
	GithubTokenExpiresAt pgtype.Timestamptz
	ID                   pgtype.UUID
}

func (q *Queries) UpdateUserGitHubTokens(ctx context.Context, arg UpdateUserGitHubTokensParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGitHubTokens,
		arg.GithubAccessToken,
		arg.GithubRefreshToken,
		arg.GithubTokenExpiresAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAccessToken,
		&i.GithubRefreshToken,
		&i.GithubTokenExpiresAt,
	)
	return i, err
}

const updateUserGithub = `-- name: UpdateUserGithub :one
UPDATE users
SET name = COALESCE(NULLIF($1::text, ''), name),
    email = COALESCE(NULLIF($2::text, ''), email),
    github_id = COALESCE(NULLIF($3::text, ''), github_id),
    github_access_token = COALESCE(NULLIF($4::text, ''), github_access_token),
    github_refresh_token = COALESCE(NULLIF($5::text, ''), github_refresh_token),
    github_token_expires_at = COALESCE($6::timestamptz, github_token_expires_at),
    updated_at = NOW()
WHERE id = $7
RETURNING id, github_id, name, email, password, created_at, updated_at, github_access_token, github_refresh_token, github_token_expires_at
`

type UpdateUserGithubParams struct {
	Name                 string
	Email                string
	GithubID             string
	GithubAccessToken    string
	GithubRefreshToken   string
	GithubTokenExpiresAt pgtype.Timestamptz
	ID                   pgtype.UUID
}

func (q *Queries) UpdateUserGithub(ctx context.Context, arg UpdateUserGithubParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGithub,
		arg.Name,
		arg.Email,
		arg.GithubID,
		arg.GithubAccessToken,
		arg.GithubRefreshToken,
		arg.GithubTokenExpiresAt,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GithubAccessToken,
		&i.GithubRefreshToken,
		&i.GithubTokenExpiresAt,
	)
	return i, err
}
